name: Deploy React App to CPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Use the node version that matches your development environment

    - name: Install Dependencies
      run: npm install

    - name: Build React Project
      run: npm run build

    - name: List build directory
      run: ls build

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.2.0 # Make sure to use the latest version
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
        server-dir: ${{ secrets.FTP_DESTINATION }}
        # Add other necessary options according to your requirements
